version: "3"
services:
  ibmcloud-audit:
    image: "ibmcloud-audit:latest"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /root/ibmcloud-audit